### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by marsjaninzmarsa** [jpedroribeiro/Baseliner#13]
[We are WebExtensions now](https://arewewebextensionsyet.com/), so it may be relatively simple. What are you thinking?

**Comment by jpedroribeiro** [comment]
Yep, it's definitely something I want to do.

**Comment by fredrikekelund** [comment]
:+1:

**Comment by jpedroribeiro** [comment]
I've just submitted an application for Baseliner to be a Firefox add-on: https://addons.mozilla.org/en-US/firefox/addon/baseliner-add-on/

I'll post on this thread whenever I get an update.

**Comment by fredrikekelund** [comment]
Looks like it's live on Firefox addons - I can install it and can confirm that it works! One issue though: the toolbar icon seems to be broken. By default it's showing some default add-on icon, not the Baseliner icon.

Another pet peeve I noticed: it says "Baseliner for Chrome" in the extension popup. Not a big deal, but maybe it would be nice to do some user agent sniffing and print Firefox instead of Chrome when applicable.

Thanks for taking the time to publish it!

**Comment by jpedroribeiro** [comment]
Yeah, good point @fredrikekelund. I'll try to get these sorted after the holidays. 
Thanks for the feedback!

**Comment by jpedroribeiro** [comment]
Ok, version 5.6 is out with fixed icon and proper wordmark. Closing this issue.
