### ISSUE TITLE
Support for tall documents

### ISSUE THREAD

**Issue by GRiMe2D** [jpedroribeiro/Baseliner#5]
Grid shown only on the top

_Wikipedia with Baseliner scrolled down_
![screen shot 2016-11-03 at 12 46 29 pm](https://cloud.githubusercontent.com/assets/6705445/19958776/a81ec436-a1c3-11e6-83f0-ce8e2ea53029.png)

**Comment by jpedroribeiro** [comment]
That's an interesting one. As far as I could see, it will depend on the website's CSS architecture.
In this case, Wikipedia sets HTML to be `height: 100%` causing it to stick to the viewport height.
![](https://cloud.githubusercontent.com/assets/1715622/20029756/4809d1f4-a34d-11e6-8eec-f838d35d1ee1.png)
Don't think there's much we can do since even targeting the HTML will be the same  outcome and I'd rather not mess with the current page's styles as not to affect the design.

I'm open to suggestions tho!

**Comment by GRiMe2D** [comment]
How about adding `window.onscroll` and moving grid up/down?

**Comment by jpedroribeiro** [comment]
The grid already covers the **entire** body element. Moving or scrolling wouldn't change anything.

**Comment by borracciaBlu** [comment]
It happened to me as well. It's the body height. So if you change it from the dev tools it should work.
@jpedroribeiro do you think it we should take care of the body height by default?

So all the time you have `height: 100%;` we have to change it `body:auto;`

```
// in dev tools 
body {
    height: auto;
}
```

**Comment by jpedroribeiro** [comment]
I guess we could add a checkbox to trigger that action, something like `Force Baseliner[]` and maybe a tooltip explaining what it does.

**Comment by jpedroribeiro** [comment]
Closing this issue as I've just published version 5.1 of Baseliner with a checkbox to force height. 
It will be publicly available in the next couple hours.

Let me know what you guys think!
